export const CHANGE_FIRST_NAME="CHANGE_FIRST_NAME"
export const CHANGE_LAST_NAME="CHANGE_LAST_NAME"

export const CHANGE_PHONE_NUMBER="CHANGE_PHONE_NUMBER"
export const CHANGE_TC_NO="CHANGE_TC_NO"
export const CHANGE_PASSWORD="CHANGE_PASSWORD"
export const CHANGE_POST_CODE="CHANGE_POST_CODE"

export const CHANGE_IBAN_NO="CHANGE_IBAN_NO"
export const CHANGE_EDUCATION_STATUS="CHANGE_EDUCATION_STATUS"
export const CHANGE_DATE_OF_BIRTH="CHANGE_DATE_OF_BIRTH"
export const CHANGE_PROFIL_PICTURE="CHANGE_PROFIL_PICTURE"
